Synchronisation cronjob made functional
ConductionNL/opencatalogi pull request #74
Opened 2024-09-18 14:38 UTC by rjzondervan

Including deleting listings that are no longer available

2024-09-18 14:50 UTC, bbrands02 commented on lib/Cron/DirectorySync.php
>          // Run once an hour
Deze comment ook niet wijzigen?

2024-09-18 14:50 UTC, bbrands02 commented on lib/Cron/DirectorySync.php
> +		var_dump('runSync');
vardump

2024-09-18 14:51 UTC, bbrands02 commented on lib/Service/DirectoryService.php
> +//		var_dump($catalogs, $url, count($localListings));
mag weg

2024-09-19 07:11 UTC, rjzondervan commented on lib/Cron/DirectorySync.php
>          // Run once an hour
Scherp, ik moet de interval weer terugzetten op een uur, 30 seconden was om snel changes te kunnen testen.

2024-09-19 07:11 UTC, rjzondervan commented on lib/Service/DirectoryService.php
> +//		var_dump($catalogs, $url, count($localListings));
Thanks, haal 'm weg.

2024-09-19 07:11 UTC, rjzondervan commented on lib/Cron/DirectorySync.php
> +		var_dump('runSync');
Thanks, haal 'm weg :)

2024-09-19 08:00 UTC, bbrands02 requested changes

2024-09-19 08:00 UTC, bbrands02 commented on lib/Service/DirectoryService.php
> +			$result = $this->client->get(uri: $url = rtrim(string: $url, characters: '/').'/apps/opencatalogi/api/directory');
Kan $url op een eigen regel ze waarde krijgen?

2024-09-19 08:27 UTC, bbrands02 approved these changes

2024-09-19 09:02 UTC, rjzondervan commented
Ter aanvulling: dit betreft een fix voor DIMOC-308

2024-09-19 09:27 UTC, WilcoLouwerse approved these changes

2024-09-19 09:27 UTC, WilcoLouwerse commented on lib/Service/DirectoryService.php
>  		//@todo get unique direcotries form the database
is this todo still relevant?

2024-09-19 09:31 UTC, rjzondervan commented on lib/Service/DirectoryService.php
>  		//@todo get unique direcotries form the database
Good question, no it isn't, will remove

2024-09-19 09:42 UTC, WilcoLouwerse approved these changes

2024-09-19 09:42 UTC, merged