Bug fixes for mongodb compatibility and length of description fields
ConductionNL/opencatalogi pull request #81
Opened 2024-09-23 12:57 UTC by rjzondervan

This contains 4 small fixes:
- Character limits are unset for description fields in SQL databases
- MongoDB Creation of metadata is fixed to prevent duplicates
- MongoDB creation of organisations is fixed
- Idem for themes

2024-09-23 13:00 UTC, bbrands02 requested changes

2024-09-23 13:00 UTC, bbrands02 commented on lib/Controller/ThemesController.php
> +			$data['_schema'] = 'organisation';
Moet het _schema hier 'theme' zijn?

2024-09-23 13:06 UTC, WilcoLouwerse requested changes
probs better to remove all var_dumps? 
Optionally you could add a description to the migration, if this is possible here just like we can do for our common-gateway repo

2024-09-23 13:06 UTC, WilcoLouwerse commented on lib/Migration/Version6Date20240923093806.php
> +				var_dump('unsetting max length');
var dump

2024-09-23 14:05 UTC, rjzondervan commented on lib/Controller/ThemesController.php
> +			$data['_schema'] = 'organisation';
Scherp, pas ik aan

2024-09-23 14:05 UTC, rjzondervan commented on lib/Migration/Version6Date20240923093806.php
> +				var_dump('unsetting max length');
Will remove

2024-09-23 14:09 UTC, WilcoLouwerse approved these changes

2024-09-23 14:25 UTC, WilcoLouwerse approved these changes

2024-09-24 12:46 UTC, bbrands02 approved these changes

2024-09-24 12:46 UTC, merged